### ISSUE TITLE
Stopped working, request update～

### ISSUE THREAD

**Issue by siukit1** [GitMyCode/d2r-chicken-bot#1]
<img width="273" alt="144770378-46cf7e82-de04-4580-b1da-2317ac1cf635" src="https://user-images.githubusercontent.com/105130703/167272058-382c03f3-cc66-4823-b92d-08e5e1080021.png">

**Comment by siukit1** [comment]
Cannot find game～～～～loop lookingforplayer

**Comment by GitMyCode** [comment]
it should be fixed now.

**Comment by rmaccc** [comment]
still doing it for me Martin, love this program btw, thank you so much

**Comment by GitMyCode** [comment]
yeah the offset changed like today

**Comment by GitMyCode** [comment]
will fix tomorrow

**Comment by GitMyCode** [comment]
https://github.com/GitMyCode/d2r-chicken-bot/releases/tag/0.11.30
